<definitions xmlns:tns="us.world_corp.my_soap_forum.wsdl" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsd1="us.world_corp.my_soap_forum.xsd" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns="http://schemas.xmlsoap.org/wsdl/" name="test" targetNamespace="us.world_corp.my_soap_forum.wsdl">
    <!--  definition of datatypes  -->
    <types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <xsd:import namespace="us.world_corp.my_soap_forum.xsd" schemaLocation="service.xsd"/>
        </schema>
    </types>
    <!--  response messages  -->
    <message name="returns_resultcode">
        <part name="resultcode" type="xsd:resultcode"/>
    </message>
    <!--  request messages  -->
    <message name="post_message">
        <part name="message" type="xsd:message"/>
    </message>
    <!--  server's services  -->
    <portType name="my SOAP forum">
        <operation name="post_message">
            <input message="tns:post_message"/>
            <output message="tns:returns_resultcode"/>
        </operation>
    </portType>
    <!--  server encoding  -->
    <binding name="my SOAP forum_webservices" type="tns:my SOAP forum">
        <soap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
        <operation name="post_message">
            <soap:operation soapAction="urn:xmethods-delayed-quotes#post_message"/>
            <input>
                <soap:body use="encoded" namespace="urn:xmethods-delayed-quotes" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
            </input>
            <output>
                <soap:body use="encoded" namespace="urn:xmethods-delayed-quotes" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
            </output>
        </operation>
    </binding>
    <!--  access to service provider  -->
    <service name="exemple">
        <port name="exemple_0" binding="my SOAP forum_webservices">
            <soap:address location="http://127.0.0.1./test_soap/endpoint1.php"/>
        </port>
        <port name="exemple_1" binding="my SOAP forum_webservices">
            <soap:address location="http://127.0.0.1./test_soap/endpoint2.php"/>
        </port>
    </service>
</definitions>